name: Deploy Frontend

on:
  push:
    branches:
      - D-Home

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on VPS (git pull & build)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/ATAL_Home
            git pull origin D-Home
            npm install --legacy-peer-deps
            npm run build
